# Use an official Node.js runtime as a parent image
FROM node:20-alpine as build

WORKDIR /app

COPY client/package.json client/package-lock.json ./client/
WORKDIR /app/client
RUN npm ci
COPY client/ ./
RUN npm run build

# Production image
FROM nginx:alpine
COPY --from=build /app/client/build /usr/share/nginx/html
COPY client/public/robots.txt /usr/share/nginx/html/robots.txt
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
