version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
      - DB_PATH=/data/database.sqlite
    volumes:
      - db-data:/data
      - ./server/config:/app/server/config
    working_dir: /app/server
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  db-data:
