[phases.setup]
nixPkgs = ["docker", "docker compose"]

[phases.install]
cmds = [
  "docker compose build"
]

[phases.build]
cmds = ["docker compose up -d"]

[start]
cmd = "docker compose up"

[variables]
PORT = "8080"
NODE_ENV = "production"
REACT_APP_API_URL = "https://halloffame-production.up.railway.app/api"
REACT_APP_STRIPE_PUBLIC_KEY = "pk_test_51RHVtNHHcwLQtpHburgmdkf6HJI0a36u6WHAb3VPv48X1nK0WUJAz5jY7aDdJVvQOwtLlJxEYzjk0SOSjFNMGQBQ00FUrbGbl3"

[persistence]
paths = ["server/database.sqlite"]